import {defineField, defineType} from 'sanity';

/**
 * Telegram Approval Log — append-only audit trail (Phase 2.15).
 *
 * One document per outbound approval request sent via Telegram. The persist
 * helper writes a `pending` row at send time; the inbound webhook receiver
 * patches `decision` + `decidedAt` + `operatorChatId` + `rawCallbackData`
 * when the operator taps Approve/Reject.
 *
 * Phase 2.15 only writes `'servicem8_portfolio'` rows. The `'blog_draft'`
 * enum value exists so Phase 2.16 can extend without a schema migration.
 *
 * IDs are auto-generated by Sanity — these rows are append-only audit
 * artifacts, not deduplicated business documents.
 */
export const telegramApprovalLog = defineType({
  name: 'telegramApprovalLog',
  title: 'Telegram Approval Log',
  type: 'document',
  groups: [{name: 'meta', title: 'Meta', default: true}],
  fields: [
    defineField({
      name: 'kind',
      type: 'string',
      title: 'Kind',
      group: 'meta',
      validation: (r) => r.required(),
      options: {
        list: [
          {title: 'ServiceM8 portfolio publish', value: 'servicem8_portfolio'},
          {title: 'Monthly AI blog draft', value: 'blog_draft'},
        ],
        layout: 'radio',
      },
      description:
        "Approval kind. Phase 2.15 only writes 'servicem8_portfolio'; 'blog_draft' is enum-only until Phase 2.16 ships the handler.",
    }),
    defineField({
      name: 'targetId',
      type: 'string',
      title: 'Target document _id',
      group: 'meta',
      validation: (r) => r.required(),
      description:
        'The _id of the document this approval is about (a servicem8Event._id, or in Phase 2.16, a blog-draft document _id).',
    }),
    defineField({
      name: 'sentMessageId',
      type: 'number',
      title: 'Sent message_id',
      group: 'meta',
      validation: (r) => r.required(),
      description:
        "Telegram's returned message_id from sendMessage. The webhook receiver looks up this row by sentMessageId on every callback.",
    }),
    defineField({
      name: 'sentChatId',
      type: 'number',
      title: 'Sent to chat_id',
      group: 'meta',
      validation: (r) => r.required(),
      description:
        'Snapshot of TELEGRAM_OPERATOR_CHAT_ID at send time. Audit field — survives an env rotation.',
    }),
    defineField({
      name: 'sentAt',
      type: 'datetime',
      title: 'Sent at',
      group: 'meta',
      validation: (r) => r.required(),
      readOnly: true,
      description: 'Server time when the message was sent.',
    }),
    defineField({
      name: 'decision',
      type: 'string',
      title: 'Decision',
      group: 'meta',
      validation: (r) => r.required(),
      options: {
        list: [
          {title: 'Pending', value: 'pending'},
          {title: 'Approve', value: 'approve'},
          {title: 'Reject', value: 'reject'},
        ],
        layout: 'radio',
      },
      initialValue: 'pending',
    }),
    defineField({
      name: 'decidedAt',
      type: 'datetime',
      title: 'Decided at',
      group: 'meta',
      description: 'Server time when the webhook callback was received.',
    }),
    defineField({
      name: 'operatorChatId',
      type: 'number',
      title: 'Operator chat_id',
      group: 'meta',
      description:
        "The chat_id of the user who tapped the button (from the callback_query's from.id). Audit snapshot.",
    }),
    defineField({
      name: 'rawCallbackData',
      type: 'string',
      title: 'Raw callback_data',
      group: 'meta',
      description: 'The exact callback_data string Telegram echoed back. For debugging.',
    }),
  ],
  preview: {
    select: {
      kind: 'kind',
      targetId: 'targetId',
      decision: 'decision',
      sentAt: 'sentAt',
    },
    prepare({kind, targetId, decision, sentAt}) {
      const title = `${kind ?? '—'} — ${targetId ?? '—'}`;
      const subtitle = [decision ?? 'pending', sentAt ?? '—']
        .filter(Boolean)
        .join(' · ');
      return {title, subtitle};
    },
  },
  orderings: [
    {
      name: 'sentDesc',
      title: 'Sent (newest first)',
      by: [{field: 'sentAt', direction: 'desc'}],
    },
  ],
});
