/**
 * Static image-import map for the audience-landing + service-detail
 * pages. Imports here are tree-shaken to the route that uses them by
 * Next/Webpack — having a single map file just keeps the page route
 * code focused on composition.
 *
 * Real photography swaps in during Phase 2.04 (Cowork sources from
 * Erick's Drive). The placeholders are generated by
 * `scripts/gen-audience-service-placeholders.mjs`.
 */

import type {StaticImageData} from 'next/image';
import type {Division} from './services';

// --- Audience heroes (3) ---
import heroResidential from '@/assets/audience/hero-residential.jpg';
import heroCommercial from '@/assets/audience/hero-commercial.jpg';
import heroHardscape from '@/assets/audience/hero-hardscape.jpg';

// --- Audience-landing project tiles (9) ---
import audProjResidential1 from '@/assets/audience/projects/residential-1.jpg';
import audProjResidential2 from '@/assets/audience/projects/residential-2.jpg';
import audProjResidential3 from '@/assets/audience/projects/residential-3.jpg';
import audProjCommercial1 from '@/assets/audience/projects/commercial-1.jpg';
import audProjCommercial2 from '@/assets/audience/projects/commercial-2.jpg';
import audProjCommercial3 from '@/assets/audience/projects/commercial-3.jpg';
import audProjHardscape1 from '@/assets/audience/projects/hardscape-1.jpg';
import audProjHardscape2 from '@/assets/audience/projects/hardscape-2.jpg';
import audProjHardscape3 from '@/assets/audience/projects/hardscape-3.jpg';

// --- Service hero photos (16) ---
import svcHeroLawnCare from '@/assets/service/hero-lawn-care.jpg';
import svcHeroLandscapeDesign from '@/assets/service/hero-landscape-design.jpg';
import svcHeroTreeServices from '@/assets/service/hero-tree-services.jpg';
import svcHeroSprinklers from '@/assets/service/hero-sprinkler-systems.jpg';
import svcHeroSnow from '@/assets/service/hero-snow-removal.jpg';
import svcHeroCleanup from '@/assets/service/hero-seasonal-cleanup.jpg';
import svcHeroLandscapeMaintenance from '@/assets/service/hero-landscape-maintenance.jpg';
import svcHeroCommercialSnow from '@/assets/service/hero-commercial-snow-removal.jpg';
import svcHeroPropertyEnh from '@/assets/service/hero-property-enhancement.jpg';
import svcHeroTurf from '@/assets/service/hero-turf-management.jpg';
import svcHeroPatios from '@/assets/service/hero-patios-walkways.jpg';
import svcHeroWalls from '@/assets/service/hero-retaining-walls.jpg';
import svcHeroFire from '@/assets/service/hero-fire-pits-features.jpg';
import svcHeroPergolas from '@/assets/service/hero-pergolas-pavilions.jpg';
import svcHeroDriveways from '@/assets/service/hero-driveways.jpg';
import svcHeroKitchens from '@/assets/service/hero-outdoor-kitchens.jpg';

// --- Waterproofing + Trenchless service heroes (6, Phase B-14) ---
// Real free-license bridge photos (docs/stock-bridge/, optimized by
// scripts/optimize-stock-bridge.mjs). Replace-by 2026-10-01 — see the
// manifest + Decisions log. These 6 slugs dropped their B-12 commercial/
// landscape imageKey aliases so they resolve to their own slug here.
import svcHeroGutterServices from '@/assets/service/hero-gutter-services.jpg';
import svcHeroYardDrainage from '@/assets/service/hero-yard-drainage.jpg';
import svcHeroFoundationRepair from '@/assets/service/hero-foundation-repair.jpg';
import svcHeroTrenchingExcavation from '@/assets/service/hero-trenching-excavation.jpg';
import svcHeroSewerLineReplacement from '@/assets/service/hero-sewer-line-replacement.jpg';
import svcHeroConduitInstallation from '@/assets/service/hero-conduit-installation.jpg';

// --- Snow Removal service heroes (4, Phase B-15) ---
// Real free-license bridge photos (docs/stock-bridge/snow-removal/, optimized
// by scripts/optimize-stock-bridge.mjs). Replace-by 2027-01-31 — see the
// manifest + Decisions log. These 4 slugs dropped their shared snow-removal/
// commercial-snow-removal imageKey aliases so they resolve to their own slug
// here; the shared assets stay in place for city/blog/resource surfaces.
import svcHeroDeIcing from '@/assets/service/hero-de-icing.jpg';
import svcHeroSidewalkShoveling from '@/assets/service/hero-sidewalk-shoveling.jpg';
import svcHeroDrivewaySnowRemoval from '@/assets/service/hero-driveway-snow-removal.jpg';
import svcHeroCommercialSnowPlowing from '@/assets/service/hero-commercial-snow-plowing.jpg';

// --- Waterproofing + Trenchless gap-service heroes (7, Phase B-16) ---
// Real free-license bridge photos (docs/stock-bridge/{waterproofing,trenchless}/,
// optimized by scripts/optimize-stock-bridge.mjs). Replace-by 2026-10-01 — see
// the manifest + Decisions log. These 7 slugs dropped their placeholder
// imageKey aliases so they resolve to their own slug here. `sump-pumps` keeps
// its alias (documented GAP — no honest free image found), and
// `handhole-pull-box` keeps its alias too: its sourced photo failed Code-phase
// verification (readable Russian signage — see the Decisions log).
import svcHeroBasementWaterproofing from '@/assets/service/hero-basement-waterproofing.jpg';
import svcHeroWindowWells from '@/assets/service/hero-window-wells.jpg';
import svcHeroCrawlSpaces from '@/assets/service/hero-crawl-spaces.jpg';
import svcHeroConcreteRaising from '@/assets/service/hero-concrete-raising.jpg';
import svcHeroHumidityControl from '@/assets/service/hero-humidity-control.jpg';
import svcHeroRadonMitigation from '@/assets/service/hero-radon-mitigation.jpg';
import svcHeroPipeFusing from '@/assets/service/hero-pipe-fusing.jpg';

// --- Service tile photos (16, used in audience-landing services grids) ---
import svcTileLawnCare from '@/assets/service/tiles/lawn-care.jpg';
import svcTileLandscapeDesign from '@/assets/service/tiles/landscape-design.jpg';
import svcTileTreeServices from '@/assets/service/tiles/tree-services.jpg';
import svcTileSprinklers from '@/assets/service/tiles/sprinkler-systems.jpg';
import svcTileSnow from '@/assets/service/tiles/snow-removal.jpg';
import svcTileCleanup from '@/assets/service/tiles/seasonal-cleanup.jpg';
import svcTileLandscapeMaintenance from '@/assets/service/tiles/landscape-maintenance.jpg';
import svcTileCommercialSnow from '@/assets/service/tiles/commercial-snow-removal.jpg';
import svcTilePropertyEnh from '@/assets/service/tiles/property-enhancement.jpg';
import svcTileTurf from '@/assets/service/tiles/turf-management.jpg';
import svcTilePatios from '@/assets/service/tiles/patios-walkways.jpg';
import svcTileWalls from '@/assets/service/tiles/retaining-walls.jpg';
import svcTileFire from '@/assets/service/tiles/fire-pits-features.jpg';
import svcTilePergolas from '@/assets/service/tiles/pergolas-pavilions.jpg';
import svcTileDriveways from '@/assets/service/tiles/driveways.jpg';
import svcTileKitchens from '@/assets/service/tiles/outdoor-kitchens.jpg';

// --- Waterproofing + Trenchless service tiles (6, Phase B-14) ---
import svcTileGutterServices from '@/assets/service/tiles/gutter-services.jpg';
import svcTileYardDrainage from '@/assets/service/tiles/yard-drainage.jpg';
import svcTileFoundationRepair from '@/assets/service/tiles/foundation-repair.jpg';
import svcTileTrenchingExcavation from '@/assets/service/tiles/trenching-excavation.jpg';
import svcTileSewerLineReplacement from '@/assets/service/tiles/sewer-line-replacement.jpg';
import svcTileConduitInstallation from '@/assets/service/tiles/conduit-installation.jpg';

// --- Snow Removal service tiles (4, Phase B-15) ---
import svcTileDeIcing from '@/assets/service/tiles/de-icing.jpg';
import svcTileSidewalkShoveling from '@/assets/service/tiles/sidewalk-shoveling.jpg';
import svcTileDrivewaySnowRemoval from '@/assets/service/tiles/driveway-snow-removal.jpg';
import svcTileCommercialSnowPlowing from '@/assets/service/tiles/commercial-snow-plowing.jpg';

// --- Waterproofing + Trenchless gap-service tiles (7, Phase B-16) ---
import svcTileBasementWaterproofing from '@/assets/service/tiles/basement-waterproofing.jpg';
import svcTileWindowWells from '@/assets/service/tiles/window-wells.jpg';
import svcTileCrawlSpaces from '@/assets/service/tiles/crawl-spaces.jpg';
import svcTileConcreteRaising from '@/assets/service/tiles/concrete-raising.jpg';
import svcTileHumidityControl from '@/assets/service/tiles/humidity-control.jpg';
import svcTileRadonMitigation from '@/assets/service/tiles/radon-mitigation.jpg';
import svcTilePipeFusing from '@/assets/service/tiles/pipe-fusing.jpg';

// --- Legacy hardscape derivatives (Phase B-16) ---
// B-16 overwrote the 4 hardscape slugs' hero/tile derivatives in place with
// stock-bridge photos (replace-by 2026-10-01). The ORIGINAL placeholder
// derivatives were preserved unchanged under `legacy/` and every non-service
// consumer (city heroes/cards, project leads, the homepage trenchless card)
// was repointed here so no stock image ever appears on a city, project, or
// homepage surface. `legacy/tiles/outdoor-kitchens.jpg` is preserved on disk
// but has no consumer, so it is deliberately not imported.
import legacyHeroWalls from '@/assets/service/legacy/hero-retaining-walls.jpg';
import legacyHeroFire from '@/assets/service/legacy/hero-fire-pits-features.jpg';
import legacyHeroDriveways from '@/assets/service/legacy/hero-driveways.jpg';
import legacyHeroKitchens from '@/assets/service/legacy/hero-outdoor-kitchens.jpg';
import legacyTileWalls from '@/assets/service/legacy/tiles/retaining-walls.jpg';
import legacyTileFire from '@/assets/service/legacy/tiles/fire-pits-features.jpg';
import legacyTileDriveways from '@/assets/service/legacy/tiles/driveways.jpg';

// --- Division-landing heroes (Phase B-15 + B-16) ---
// Override the generic audience-hero aliases (see DIVISION_HERO below).
// snow-removal replace-by 2027-01-31; waterproofing 2026-10-01. The B-16
// trenchless landing hero was NOT wired: its sourced photo failed Code-phase
// verification (readable "BARANGAY AYALA ALABANG" shirt print geolocates the
// scene — see the Decisions log); /trenchless keeps its audience alias.
import divisionHeroSnowRemoval from '@/assets/division/hero-snow-removal.jpg';
import divisionHeroWaterproofing from '@/assets/division/hero-waterproofing.jpg';

// --- About brand-story portrait (Phase 1.12, reused as Phase 1.14 WhyLocal portrait) ---
import aboutPortrait from '@/assets/about/brand-story.jpg';

// --- Service-detail featured project tiles (~30) ---
import sp_lc1 from '@/assets/service/projects/lawn-care-1.jpg';
import sp_lc2 from '@/assets/service/projects/lawn-care-2.jpg';
import sp_ld1 from '@/assets/service/projects/landscape-design-1.jpg';
import sp_ld2 from '@/assets/service/projects/landscape-design-2.jpg';
import sp_ld3 from '@/assets/service/projects/landscape-design-3.jpg';
import sp_ts1 from '@/assets/service/projects/tree-services-1.jpg';
import sp_ts2 from '@/assets/service/projects/tree-services-2.jpg';
import sp_ss1 from '@/assets/service/projects/sprinkler-systems-1.jpg';
import sp_ss2 from '@/assets/service/projects/sprinkler-systems-2.jpg';
import sp_sr1 from '@/assets/service/projects/snow-removal-1.jpg';
import sp_sr2 from '@/assets/service/projects/snow-removal-2.jpg';
import sp_sc1 from '@/assets/service/projects/seasonal-cleanup-1.jpg';
import sp_sc2 from '@/assets/service/projects/seasonal-cleanup-2.jpg';
import sp_lm1 from '@/assets/service/projects/landscape-maintenance-1.jpg';
import sp_lm2 from '@/assets/service/projects/landscape-maintenance-2.jpg';
import sp_csr1 from '@/assets/service/projects/commercial-snow-removal-1.jpg';
import sp_csr2 from '@/assets/service/projects/commercial-snow-removal-2.jpg';
import sp_pe1 from '@/assets/service/projects/property-enhancement-1.jpg';
import sp_pe2 from '@/assets/service/projects/property-enhancement-2.jpg';
import sp_tm1 from '@/assets/service/projects/turf-management-1.jpg';
import sp_tm2 from '@/assets/service/projects/turf-management-2.jpg';
import sp_pw1 from '@/assets/service/projects/patios-walkways-1.jpg';
import sp_pw2 from '@/assets/service/projects/patios-walkways-2.jpg';
import sp_pw3 from '@/assets/service/projects/patios-walkways-3.jpg';
import sp_rw1 from '@/assets/service/projects/retaining-walls-1.jpg';
import sp_rw2 from '@/assets/service/projects/retaining-walls-2.jpg';
import sp_fpf1 from '@/assets/service/projects/fire-pits-features-1.jpg';
import sp_fpf2 from '@/assets/service/projects/fire-pits-features-2.jpg';
import sp_pp1 from '@/assets/service/projects/pergolas-pavilions-1.jpg';
import sp_pp2 from '@/assets/service/projects/pergolas-pavilions-2.jpg';
import sp_dw1 from '@/assets/service/projects/driveways-1.jpg';
import sp_dw2 from '@/assets/service/projects/driveways-2.jpg';
import sp_ok1 from '@/assets/service/projects/outdoor-kitchens-1.jpg';
import sp_ok2 from '@/assets/service/projects/outdoor-kitchens-2.jpg';

export const AUDIENCE_HERO: Record<'residential' | 'commercial' | 'hardscape', StaticImageData> = {
  residential: heroResidential,
  commercial: heroCommercial,
  hardscape: heroHardscape,
};

export const AUDIENCE_PROJECT_TILES: Record<'residential' | 'commercial' | 'hardscape', StaticImageData[]> = {
  residential: [audProjResidential1, audProjResidential2, audProjResidential3],
  commercial: [audProjCommercial1, audProjCommercial2, audProjCommercial3],
  hardscape: [audProjHardscape1, audProjHardscape2, audProjHardscape3],
};

export const SERVICE_HERO: Record<string, StaticImageData> = {
  'lawn-care': svcHeroLawnCare,
  'landscape-design': svcHeroLandscapeDesign,
  'tree-services': svcHeroTreeServices,
  'sprinkler-systems': svcHeroSprinklers,
  'snow-removal': svcHeroSnow,
  'seasonal-cleanup': svcHeroCleanup,
  'landscape-maintenance': svcHeroLandscapeMaintenance,
  'commercial-snow-removal': svcHeroCommercialSnow,
  'property-enhancement': svcHeroPropertyEnh,
  'turf-management': svcHeroTurf,
  'patios-walkways': svcHeroPatios,
  'retaining-walls': svcHeroWalls,
  'fire-pits-features': svcHeroFire,
  'pergolas-pavilions': svcHeroPergolas,
  driveways: svcHeroDriveways,
  'outdoor-kitchens': svcHeroKitchens,
  // Phase B-14 — Waterproofing + Trenchless bridge photos (real, replace-by 2026-10-01).
  'gutter-services': svcHeroGutterServices,
  'yard-drainage': svcHeroYardDrainage,
  'foundation-repair': svcHeroFoundationRepair,
  'trenching-excavation': svcHeroTrenchingExcavation,
  'sewer-line-replacement': svcHeroSewerLineReplacement,
  'conduit-installation': svcHeroConduitInstallation,
  // Phase B-15 — Snow Removal bridge photos (real, replace-by 2027-01-31).
  'de-icing': svcHeroDeIcing,
  'sidewalk-shoveling': svcHeroSidewalkShoveling,
  'driveway-snow-removal': svcHeroDrivewaySnowRemoval,
  'commercial-snow-plowing': svcHeroCommercialSnowPlowing,
  // Phase B-16 — Waterproofing + Trenchless gap-service bridge photos
  // (real, replace-by 2026-10-01). The 4 hardscape slugs above were
  // overwritten in place the same phase (originals in legacy/).
  'basement-waterproofing': svcHeroBasementWaterproofing,
  'window-wells': svcHeroWindowWells,
  'crawl-spaces': svcHeroCrawlSpaces,
  'concrete-raising': svcHeroConcreteRaising,
  'humidity-control': svcHeroHumidityControl,
  'radon-mitigation': svcHeroRadonMitigation,
  'pipe-fusing': svcHeroPipeFusing,
  // B-16 — missile-boring (diagram track, untouched page) aliased
  // imageKey 'driveways' before that key became a stock photo; its alias
  // moved to this legacy key so the page keeps its exact pre-B-16 image.
  'legacy-driveways': legacyHeroDriveways,
};

export const SERVICE_TILE: Record<string, StaticImageData> = {
  'lawn-care': svcTileLawnCare,
  'landscape-design': svcTileLandscapeDesign,
  'tree-services': svcTileTreeServices,
  'sprinkler-systems': svcTileSprinklers,
  'snow-removal': svcTileSnow,
  'seasonal-cleanup': svcTileCleanup,
  'landscape-maintenance': svcTileLandscapeMaintenance,
  'commercial-snow-removal': svcTileCommercialSnow,
  'property-enhancement': svcTilePropertyEnh,
  'turf-management': svcTileTurf,
  'patios-walkways': svcTilePatios,
  'retaining-walls': svcTileWalls,
  'fire-pits-features': svcTileFire,
  'pergolas-pavilions': svcTilePergolas,
  driveways: svcTileDriveways,
  'outdoor-kitchens': svcTileKitchens,
  // Phase B-14 — Waterproofing + Trenchless bridge photos (real, replace-by 2026-10-01).
  'gutter-services': svcTileGutterServices,
  'yard-drainage': svcTileYardDrainage,
  'foundation-repair': svcTileFoundationRepair,
  'trenching-excavation': svcTileTrenchingExcavation,
  'sewer-line-replacement': svcTileSewerLineReplacement,
  'conduit-installation': svcTileConduitInstallation,
  // Phase B-15 — Snow Removal bridge photos (real, replace-by 2027-01-31).
  'de-icing': svcTileDeIcing,
  'sidewalk-shoveling': svcTileSidewalkShoveling,
  'driveway-snow-removal': svcTileDrivewaySnowRemoval,
  'commercial-snow-plowing': svcTileCommercialSnowPlowing,
  // Phase B-16 — Waterproofing + Trenchless gap-service bridge photos
  // (real, replace-by 2026-10-01).
  'basement-waterproofing': svcTileBasementWaterproofing,
  'window-wells': svcTileWindowWells,
  'crawl-spaces': svcTileCrawlSpaces,
  'concrete-raising': svcTileConcreteRaising,
  'humidity-control': svcTileHumidityControl,
  'radon-mitigation': svcTileRadonMitigation,
  'pipe-fusing': svcTilePipeFusing,
  // B-16 — see the SERVICE_HERO legacy-driveways note (missile-boring alias).
  'legacy-driveways': legacyTileDriveways,
};

/**
 * Phase B-15 + B-16 — per-division landing-hero override. When a division
 * has an entry here, the `/[locale]/[division]/` landing resolves its hero
 * from this map INSTEAD of the `AUDIENCE_HERO[DIVISION_META.heroImageKey]`
 * audience-alias fallback — the consumer reads
 * `DIVISION_HERO[division] ?? AUDIENCE_HERO[meta.heroImageKey]`.
 *
 * snow-removal (B-15, replace-by 2027-01-31) and waterproofing (B-16,
 * replace-by 2026-10-01) override their generic audience-alias photos with
 * real free-license bridge photos. landscape, hardscape and trenchless have
 * no entry and keep resolving through their audience alias, unchanged
 * (the sourced trenchless hero failed B-16 Code verification — see the
 * Decisions log).
 */
export const DIVISION_HERO: Partial<Record<Division, StaticImageData>> = {
  'snow-removal': divisionHeroSnowRemoval,
  waterproofing: divisionHeroWaterproofing,
};

/**
 * Phase M.10 — per-city hero photos. Every one of the 22 surfaced cities
 * (plus the 2 retired) now resolves to a DISTINCT real Sunset Services
 * photo so no two cities share an image. Picks were varied across the
 * existing photo corpus to give each city a visual identity; Erick's
 * M.03 city-specific photography will swap in over these placeholders by
 * editing this map only (no consumer changes needed).
 */
export const LOCATION_HERO: Record<string, StaticImageData> = {
  aurora: heroHardscape,
  naperville: heroResidential,
  batavia: svcHeroLandscapeDesign,
  wheaton: svcHeroLawnCare,
  lisle: heroCommercial,
  bolingbrook: svcHeroCommercialSnow,
  hinsdale: svcHeroPergolas,
  // B-16: the six hardscape-derived city picks moved to the preserved
  // legacy/ copies when the live derivatives became stock photos — each
  // city keeps rendering its exact pre-B-16 image, byte-identical.
  'oak-brook': legacyHeroKitchens,
  elmhurst: svcHeroPatios,
  'clarendon-hills': legacyHeroFire,
  'burr-ridge': legacyHeroDriveways,
  'western-springs': svcHeroLandscapeMaintenance,
  'glen-ellyn': svcHeroTreeServices,
  'downers-grove': svcHeroPropertyEnh,
  winfield: svcHeroTurf,
  lombard: legacyHeroWalls,
  'st-charles': svcHeroSnow,
  geneva: svcHeroCleanup,
  'south-elgin': svcHeroSprinklers,
  elburn: svcTileLawnCare,
  'north-aurora': svcTileLandscapeDesign,
  oswego: svcTilePatios,
  yorkville: legacyTileFire,
  plainfield: legacyTileWalls,
};

/**
 * Phase M.10 — cities-grid card photos. Mirrors `LOCATION_HERO` so each
 * city's identity is consistent across the index card and the detail
 * page hero.
 */
export const LOCATION_CARD: Record<string, StaticImageData> = {
  aurora: heroHardscape,
  naperville: heroResidential,
  batavia: svcHeroLandscapeDesign,
  wheaton: svcHeroLawnCare,
  lisle: heroCommercial,
  bolingbrook: svcHeroCommercialSnow,
  hinsdale: svcHeroPergolas,
  // B-16: mirrors LOCATION_HERO — legacy/ copies keep the cards identical.
  'oak-brook': legacyHeroKitchens,
  elmhurst: svcHeroPatios,
  'clarendon-hills': legacyHeroFire,
  'burr-ridge': legacyHeroDriveways,
  'western-springs': svcHeroLandscapeMaintenance,
  'glen-ellyn': svcHeroTreeServices,
  'downers-grove': svcHeroPropertyEnh,
  winfield: svcHeroTurf,
  lombard: legacyHeroWalls,
  'st-charles': svcHeroSnow,
  geneva: svcHeroCleanup,
  'south-elgin': svcHeroSprinklers,
  elburn: svcTileLawnCare,
  'north-aurora': svcTileLandscapeDesign,
  oswego: svcTilePatios,
  yorkville: legacyTileFire,
  plainfield: legacyTileWalls,
};

/**
 * Phase 1.14 — local-projects strip placeholders. Each city aliases to an
 * existing audience project-tile triplet; Phase 1.16 wires real projects.
 */
export const LOCATION_PROJECT_TILES: Record<string, StaticImageData[]> = {
  aurora: [audProjResidential1, audProjResidential2, audProjResidential3],
  naperville: [audProjHardscape1, audProjHardscape2, audProjHardscape3],
  batavia: [audProjResidential1, audProjResidential2, audProjResidential3],
  wheaton: [audProjResidential1, audProjResidential2, audProjResidential3],
  lisle: [audProjCommercial1, audProjCommercial2, audProjCommercial3],
  bolingbrook: [audProjCommercial1, audProjCommercial2, audProjCommercial3],
  hinsdale: [audProjResidential1, audProjResidential2, audProjResidential3],
  'oak-brook': [audProjCommercial1, audProjCommercial2, audProjCommercial3],
  elmhurst: [audProjResidential1, audProjResidential2, audProjResidential3],
  'clarendon-hills': [audProjResidential1, audProjResidential2, audProjResidential3],
  'burr-ridge': [audProjHardscape1, audProjHardscape2, audProjHardscape3],
  'western-springs': [audProjResidential1, audProjResidential2, audProjResidential3],
  'glen-ellyn': [audProjResidential1, audProjResidential2, audProjResidential3],
  'downers-grove': [audProjCommercial1, audProjCommercial2, audProjCommercial3],
  winfield: [audProjResidential1, audProjResidential2, audProjResidential3],
  lombard: [audProjHardscape1, audProjHardscape2, audProjHardscape3],
  'st-charles': [audProjResidential1, audProjResidential2, audProjResidential3],
  geneva: [audProjResidential1, audProjResidential2, audProjResidential3],
  'south-elgin': [audProjResidential1, audProjResidential2, audProjResidential3],
  elburn: [audProjResidential1, audProjResidential2, audProjResidential3],
  'north-aurora': [audProjCommercial1, audProjCommercial2, audProjCommercial3],
  oswego: [audProjHardscape1, audProjHardscape2, audProjHardscape3],
  yorkville: [audProjHardscape1, audProjHardscape2, audProjHardscape3],
  plainfield: [audProjCommercial1, audProjCommercial2, audProjCommercial3],
};

/** Phase 1.14 — shared portrait for the WhyLocalPanel across all 6 cities. */
export const LOCATION_PORTRAIT: StaticImageData = aboutPortrait;

/**
 * Phase 1.16 — projects portfolio asset aliases.
 *
 * Each of the 12 placeholder projects aliases to existing audience-project
 * + service-project sharp-generated tiles. Phase 2.04 swaps to real
 * per-project photography by editing only these maps; the canonical
 * Phase 2 path is `/public/images/projects/{slug}/{lead,01..08,before,after}.avif`
 * (handover §6.3) — Cowork drops files there and updates this file.
 */
export const PROJECT_LEAD: Record<string, StaticImageData> = {
  'naperville-hilltop-terrace': svcTilePatios,
  // B-16: fire/driveways/walls leads moved to the preserved legacy/ copies —
  // stock imagery must never imply Sunset attribution on a project surface.
  'naperville-fire-court': legacyTileFire,
  'aurora-hoa-curb-refresh': svcTileLawnCare,
  'aurora-driveway-apron': legacyTileDriveways,
  'wheaton-lawn-reset': svcTileLawnCare,
  'wheaton-bank-frontage': svcTileLandscapeMaintenance,
  'lisle-retaining-wall': legacyTileWalls,
  'lisle-backyard-refresh': svcTileLandscapeDesign,
  'batavia-garden-reset': svcTileLandscapeDesign,
  'batavia-front-walk': svcTilePatios,
  'bolingbrook-office-court': svcTilePropertyEnh,
  'bolingbrook-paver-plaza': svcTilePatios,
};

export const PROJECT_GALLERY: Record<string, StaticImageData[]> = {
  // Hardscape · 8 photos · patios + walls + fire mix
  'naperville-hilltop-terrace': [
    sp_pw1,
    sp_pw2,
    sp_pw3,
    sp_rw1,
    sp_rw2,
    sp_fpf1,
    sp_fpf2,
    audProjHardscape1,
  ],
  // Hardscape · 5 photos
  'naperville-fire-court': [sp_fpf1, sp_fpf2, sp_pw1, sp_pw2, audProjHardscape2],
  // Commercial · 6 photos
  'aurora-hoa-curb-refresh': [sp_lc1, sp_lc2, sp_ld1, sp_ld2, sp_ld3, audProjCommercial1],
  // Hardscape · 4 photos
  'aurora-driveway-apron': [sp_pw1, sp_pw2, sp_pw3, sp_dw1],
  // Residential · 5 photos
  'wheaton-lawn-reset': [sp_lc1, sp_lc2, sp_ss1, sp_ss2, audProjResidential1],
  // Commercial · 4 photos
  'wheaton-bank-frontage': [sp_lm1, sp_lm2, sp_lc1, audProjCommercial2],
  // Hardscape · 5 photos
  'lisle-retaining-wall': [sp_rw1, sp_rw2, sp_pw1, sp_pw2, audProjHardscape3],
  // Residential · 4 photos
  'lisle-backyard-refresh': [sp_ld1, sp_ld2, sp_lc1, audProjResidential2],
  // Residential · 4 photos
  'batavia-garden-reset': [sp_ld1, sp_ld2, sp_ld3, audProjResidential3],
  // Residential · 4 photos
  'batavia-front-walk': [sp_pw1, sp_pw2, sp_pw3, audProjResidential1],
  // Commercial · 5 photos
  'bolingbrook-office-court': [sp_lc1, sp_lc2, sp_ld1, sp_pe1, sp_pe2],
  // Hardscape · 6 photos
  'bolingbrook-paver-plaza': [sp_pw1, sp_pw2, sp_pw3, sp_rw1, sp_rw2, audProjHardscape1],
};

export const PROJECT_BEFORE_AFTER: Record<
  string,
  {before: StaticImageData; after: StaticImageData}
> = {
  'naperville-hilltop-terrace': {before: audProjHardscape3, after: sp_pw1},
  'aurora-hoa-curb-refresh': {before: audProjCommercial3, after: sp_lc1},
};

export const SERVICE_PROJECT: Record<string, StaticImageData> = {
  'lawn-care-1': sp_lc1,
  'lawn-care-2': sp_lc2,
  'landscape-design-1': sp_ld1,
  'landscape-design-2': sp_ld2,
  'landscape-design-3': sp_ld3,
  'tree-services-1': sp_ts1,
  'tree-services-2': sp_ts2,
  'sprinkler-systems-1': sp_ss1,
  'sprinkler-systems-2': sp_ss2,
  'snow-removal-1': sp_sr1,
  'snow-removal-2': sp_sr2,
  'seasonal-cleanup-1': sp_sc1,
  'seasonal-cleanup-2': sp_sc2,
  'landscape-maintenance-1': sp_lm1,
  'landscape-maintenance-2': sp_lm2,
  'commercial-snow-removal-1': sp_csr1,
  'commercial-snow-removal-2': sp_csr2,
  'property-enhancement-1': sp_pe1,
  'property-enhancement-2': sp_pe2,
  'turf-management-1': sp_tm1,
  'turf-management-2': sp_tm2,
  'patios-walkways-1': sp_pw1,
  'patios-walkways-2': sp_pw2,
  'patios-walkways-3': sp_pw3,
  'retaining-walls-1': sp_rw1,
  'retaining-walls-2': sp_rw2,
  'fire-pits-features-1': sp_fpf1,
  'fire-pits-features-2': sp_fpf2,
  'pergolas-pavilions-1': sp_pp1,
  'pergolas-pavilions-2': sp_pp2,
  'driveways-1': sp_dw1,
  'driveways-2': sp_dw2,
  'outdoor-kitchens-1': sp_ok1,
  'outdoor-kitchens-2': sp_ok2,
};
