/**
 * Static image-import map for the audience-landing + service-detail
 * pages. Imports here are tree-shaken to the route that uses them by
 * Next/Webpack — having a single map file just keeps the page route
 * code focused on composition.
 *
 * Real photography swaps in during Phase 2.04 (Cowork sources from
 * Erick's Drive). The placeholders are generated by
 * `scripts/gen-audience-service-placeholders.mjs`.
 */

import type {StaticImageData} from 'next/image';

// --- Audience heroes (3) ---
import heroResidential from '@/assets/audience/hero-residential.jpg';
import heroCommercial from '@/assets/audience/hero-commercial.jpg';
import heroHardscape from '@/assets/audience/hero-hardscape.jpg';

// --- Audience-landing project tiles (9) ---
import audProjResidential1 from '@/assets/audience/projects/residential-1.jpg';
import audProjResidential2 from '@/assets/audience/projects/residential-2.jpg';
import audProjResidential3 from '@/assets/audience/projects/residential-3.jpg';
import audProjCommercial1 from '@/assets/audience/projects/commercial-1.jpg';
import audProjCommercial2 from '@/assets/audience/projects/commercial-2.jpg';
import audProjCommercial3 from '@/assets/audience/projects/commercial-3.jpg';
import audProjHardscape1 from '@/assets/audience/projects/hardscape-1.jpg';
import audProjHardscape2 from '@/assets/audience/projects/hardscape-2.jpg';
import audProjHardscape3 from '@/assets/audience/projects/hardscape-3.jpg';

// --- Service hero photos (16) ---
import svcHeroLawnCare from '@/assets/service/hero-lawn-care.jpg';
import svcHeroLandscapeDesign from '@/assets/service/hero-landscape-design.jpg';
import svcHeroTreeServices from '@/assets/service/hero-tree-services.jpg';
import svcHeroSprinklers from '@/assets/service/hero-sprinkler-systems.jpg';
import svcHeroSnow from '@/assets/service/hero-snow-removal.jpg';
import svcHeroCleanup from '@/assets/service/hero-seasonal-cleanup.jpg';
import svcHeroLandscapeMaintenance from '@/assets/service/hero-landscape-maintenance.jpg';
import svcHeroCommercialSnow from '@/assets/service/hero-commercial-snow-removal.jpg';
import svcHeroPropertyEnh from '@/assets/service/hero-property-enhancement.jpg';
import svcHeroTurf from '@/assets/service/hero-turf-management.jpg';
import svcHeroPatios from '@/assets/service/hero-patios-walkways.jpg';
import svcHeroWalls from '@/assets/service/hero-retaining-walls.jpg';
import svcHeroFire from '@/assets/service/hero-fire-pits-features.jpg';
import svcHeroPergolas from '@/assets/service/hero-pergolas-pavilions.jpg';
import svcHeroDriveways from '@/assets/service/hero-driveways.jpg';
import svcHeroKitchens from '@/assets/service/hero-outdoor-kitchens.jpg';

// --- Service tile photos (16, used in audience-landing services grids) ---
import svcTileLawnCare from '@/assets/service/tiles/lawn-care.jpg';
import svcTileLandscapeDesign from '@/assets/service/tiles/landscape-design.jpg';
import svcTileTreeServices from '@/assets/service/tiles/tree-services.jpg';
import svcTileSprinklers from '@/assets/service/tiles/sprinkler-systems.jpg';
import svcTileSnow from '@/assets/service/tiles/snow-removal.jpg';
import svcTileCleanup from '@/assets/service/tiles/seasonal-cleanup.jpg';
import svcTileLandscapeMaintenance from '@/assets/service/tiles/landscape-maintenance.jpg';
import svcTileCommercialSnow from '@/assets/service/tiles/commercial-snow-removal.jpg';
import svcTilePropertyEnh from '@/assets/service/tiles/property-enhancement.jpg';
import svcTileTurf from '@/assets/service/tiles/turf-management.jpg';
import svcTilePatios from '@/assets/service/tiles/patios-walkways.jpg';
import svcTileWalls from '@/assets/service/tiles/retaining-walls.jpg';
import svcTileFire from '@/assets/service/tiles/fire-pits-features.jpg';
import svcTilePergolas from '@/assets/service/tiles/pergolas-pavilions.jpg';
import svcTileDriveways from '@/assets/service/tiles/driveways.jpg';
import svcTileKitchens from '@/assets/service/tiles/outdoor-kitchens.jpg';

// --- About brand-story portrait (Phase 1.12, reused as Phase 1.14 WhyLocal portrait) ---
import aboutPortrait from '@/assets/about/brand-story.jpg';

// --- Service-detail featured project tiles (~30) ---
import sp_lc1 from '@/assets/service/projects/lawn-care-1.jpg';
import sp_lc2 from '@/assets/service/projects/lawn-care-2.jpg';
import sp_ld1 from '@/assets/service/projects/landscape-design-1.jpg';
import sp_ld2 from '@/assets/service/projects/landscape-design-2.jpg';
import sp_ld3 from '@/assets/service/projects/landscape-design-3.jpg';
import sp_ts1 from '@/assets/service/projects/tree-services-1.jpg';
import sp_ts2 from '@/assets/service/projects/tree-services-2.jpg';
import sp_ss1 from '@/assets/service/projects/sprinkler-systems-1.jpg';
import sp_ss2 from '@/assets/service/projects/sprinkler-systems-2.jpg';
import sp_sr1 from '@/assets/service/projects/snow-removal-1.jpg';
import sp_sr2 from '@/assets/service/projects/snow-removal-2.jpg';
import sp_sc1 from '@/assets/service/projects/seasonal-cleanup-1.jpg';
import sp_sc2 from '@/assets/service/projects/seasonal-cleanup-2.jpg';
import sp_lm1 from '@/assets/service/projects/landscape-maintenance-1.jpg';
import sp_lm2 from '@/assets/service/projects/landscape-maintenance-2.jpg';
import sp_csr1 from '@/assets/service/projects/commercial-snow-removal-1.jpg';
import sp_csr2 from '@/assets/service/projects/commercial-snow-removal-2.jpg';
import sp_pe1 from '@/assets/service/projects/property-enhancement-1.jpg';
import sp_pe2 from '@/assets/service/projects/property-enhancement-2.jpg';
import sp_tm1 from '@/assets/service/projects/turf-management-1.jpg';
import sp_tm2 from '@/assets/service/projects/turf-management-2.jpg';
import sp_pw1 from '@/assets/service/projects/patios-walkways-1.jpg';
import sp_pw2 from '@/assets/service/projects/patios-walkways-2.jpg';
import sp_pw3 from '@/assets/service/projects/patios-walkways-3.jpg';
import sp_rw1 from '@/assets/service/projects/retaining-walls-1.jpg';
import sp_rw2 from '@/assets/service/projects/retaining-walls-2.jpg';
import sp_fpf1 from '@/assets/service/projects/fire-pits-features-1.jpg';
import sp_fpf2 from '@/assets/service/projects/fire-pits-features-2.jpg';
import sp_pp1 from '@/assets/service/projects/pergolas-pavilions-1.jpg';
import sp_pp2 from '@/assets/service/projects/pergolas-pavilions-2.jpg';
import sp_dw1 from '@/assets/service/projects/driveways-1.jpg';
import sp_dw2 from '@/assets/service/projects/driveways-2.jpg';
import sp_ok1 from '@/assets/service/projects/outdoor-kitchens-1.jpg';
import sp_ok2 from '@/assets/service/projects/outdoor-kitchens-2.jpg';

export const AUDIENCE_HERO: Record<'residential' | 'commercial' | 'hardscape', StaticImageData> = {
  residential: heroResidential,
  commercial: heroCommercial,
  hardscape: heroHardscape,
};

export const AUDIENCE_PROJECT_TILES: Record<'residential' | 'commercial' | 'hardscape', StaticImageData[]> = {
  residential: [audProjResidential1, audProjResidential2, audProjResidential3],
  commercial: [audProjCommercial1, audProjCommercial2, audProjCommercial3],
  hardscape: [audProjHardscape1, audProjHardscape2, audProjHardscape3],
};

export const SERVICE_HERO: Record<string, StaticImageData> = {
  'lawn-care': svcHeroLawnCare,
  'landscape-design': svcHeroLandscapeDesign,
  'tree-services': svcHeroTreeServices,
  'sprinkler-systems': svcHeroSprinklers,
  'snow-removal': svcHeroSnow,
  'seasonal-cleanup': svcHeroCleanup,
  'landscape-maintenance': svcHeroLandscapeMaintenance,
  'commercial-snow-removal': svcHeroCommercialSnow,
  'property-enhancement': svcHeroPropertyEnh,
  'turf-management': svcHeroTurf,
  'patios-walkways': svcHeroPatios,
  'retaining-walls': svcHeroWalls,
  'fire-pits-features': svcHeroFire,
  'pergolas-pavilions': svcHeroPergolas,
  driveways: svcHeroDriveways,
  'outdoor-kitchens': svcHeroKitchens,
};

export const SERVICE_TILE: Record<string, StaticImageData> = {
  'lawn-care': svcTileLawnCare,
  'landscape-design': svcTileLandscapeDesign,
  'tree-services': svcTileTreeServices,
  'sprinkler-systems': svcTileSprinklers,
  'snow-removal': svcTileSnow,
  'seasonal-cleanup': svcTileCleanup,
  'landscape-maintenance': svcTileLandscapeMaintenance,
  'commercial-snow-removal': svcTileCommercialSnow,
  'property-enhancement': svcTilePropertyEnh,
  'turf-management': svcTileTurf,
  'patios-walkways': svcTilePatios,
  'retaining-walls': svcTileWalls,
  'fire-pits-features': svcTileFire,
  'pergolas-pavilions': svcTilePergolas,
  driveways: svcTileDriveways,
  'outdoor-kitchens': svcTileKitchens,
};

/**
 * Phase 1.14 — location-page hero photos. Each city aliases to an existing
 * audience hero placeholder for Part 1; Phase 2.04 swaps to real city
 * photography sourced from Erick's Drive (per Phase 1.13 §7 brief).
 */
export const LOCATION_HERO: Record<string, StaticImageData> = {
  aurora: heroResidential,
  naperville: heroHardscape,
  batavia: heroResidential,
  wheaton: heroResidential,
  lisle: heroCommercial,
  bolingbrook: heroCommercial,
};

/**
 * Phase 1.14 — cities-grid card photos on the Service Areas index. Aliases
 * to the same audience heroes; Phase 2.04 swaps to per-city assets.
 */
export const LOCATION_CARD: Record<string, StaticImageData> = {
  aurora: heroResidential,
  naperville: heroHardscape,
  batavia: heroResidential,
  wheaton: heroResidential,
  lisle: heroCommercial,
  bolingbrook: heroCommercial,
};

/**
 * Phase 1.14 — local-projects strip placeholders. Each city aliases to an
 * existing audience project-tile triplet; Phase 1.16 wires real projects.
 */
export const LOCATION_PROJECT_TILES: Record<string, StaticImageData[]> = {
  aurora: [audProjResidential1, audProjResidential2, audProjResidential3],
  naperville: [audProjHardscape1, audProjHardscape2, audProjHardscape3],
  batavia: [audProjResidential1, audProjResidential2, audProjResidential3],
  wheaton: [audProjResidential1, audProjResidential2, audProjResidential3],
  lisle: [audProjCommercial1, audProjCommercial2, audProjCommercial3],
  bolingbrook: [audProjCommercial1, audProjCommercial2, audProjCommercial3],
};

/** Phase 1.14 — shared portrait for the WhyLocalPanel across all 6 cities. */
export const LOCATION_PORTRAIT: StaticImageData = aboutPortrait;

export const SERVICE_PROJECT: Record<string, StaticImageData> = {
  'lawn-care-1': sp_lc1,
  'lawn-care-2': sp_lc2,
  'landscape-design-1': sp_ld1,
  'landscape-design-2': sp_ld2,
  'landscape-design-3': sp_ld3,
  'tree-services-1': sp_ts1,
  'tree-services-2': sp_ts2,
  'sprinkler-systems-1': sp_ss1,
  'sprinkler-systems-2': sp_ss2,
  'snow-removal-1': sp_sr1,
  'snow-removal-2': sp_sr2,
  'seasonal-cleanup-1': sp_sc1,
  'seasonal-cleanup-2': sp_sc2,
  'landscape-maintenance-1': sp_lm1,
  'landscape-maintenance-2': sp_lm2,
  'commercial-snow-removal-1': sp_csr1,
  'commercial-snow-removal-2': sp_csr2,
  'property-enhancement-1': sp_pe1,
  'property-enhancement-2': sp_pe2,
  'turf-management-1': sp_tm1,
  'turf-management-2': sp_tm2,
  'patios-walkways-1': sp_pw1,
  'patios-walkways-2': sp_pw2,
  'patios-walkways-3': sp_pw3,
  'retaining-walls-1': sp_rw1,
  'retaining-walls-2': sp_rw2,
  'fire-pits-features-1': sp_fpf1,
  'fire-pits-features-2': sp_fpf2,
  'pergolas-pavilions-1': sp_pp1,
  'pergolas-pavilions-2': sp_pp2,
  'driveways-1': sp_dw1,
  'driveways-2': sp_dw2,
  'outdoor-kitchens-1': sp_ok1,
  'outdoor-kitchens-2': sp_ok2,
};
